name: Build and Release
run-name: ${{ github.actor }} build 🚀

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Container
        run: |
          # Chạy docker compose trên chính VPS của bạn
          docker compose up -d --build --remove-orphans